const pptxgen = require('pptxgenjs');
const pptx = new pptxgen();
pptx.layout = 'LAYOUT_WIDE';
pptx.author = 'HandoffGuard';
pptx.subject = 'IBM Bob 2.0 Hackathon';
pptx.title = 'HandoffGuard - Resume AI coding work only from a verified repository state';
pptx.company = 'Hackathon prototype';
pptx.lang = 'en-US';
pptx.theme = { headFontFace: 'Aptos Display', bodyFontFace: 'Aptos', lang: 'en-US' };
const C={bg:'0B1020',panel:'121A2E',text:'F6F8FF',muted:'A9B7D4',line:'2B3858',blue:'7CA6FF',cyan:'55D8FF',green:'72E6A6',amber:'FFD166',red:'FF7B86'};
pptx.defineSlideMaster({title:'MASTER',background:{color:C.bg},objects:[
 {rect:{x:0.45,y:0.32,w:0.13,h:0.13,fill:{color:C.cyan},line:{color:C.cyan}}},
 {text:{text:'HANDOFFGUARD  /  IBM BOB 2.0 HACKATHON',options:{x:0.68,y:0.22,w:5.0,h:0.3,fontFace:'Aptos',fontSize:10,bold:true,color:C.muted,charSpacing:1.1,margin:0}}},
 {text:{text:'Preserve accepted state. Re-verify mutable facts.',options:{x:8.2,y:7.06,w:4.6,h:0.22,fontFace:'Aptos',fontSize:9,color:'6F7D99',align:'right',margin:0}}}
],slideNumber:{x:12.75,y:0.22,color:'6F7D99',fontFace:'Aptos',fontSize:9}});
function title(s,t,sub=''){s.addText(t,{x:0.65,y:0.8,w:11.9,h:0.65,fontFace:'Aptos Display',fontSize:30,bold:true,color:C.text,margin:0,fit:'shrink'});if(sub)s.addText(sub,{x:0.65,y:1.52,w:11.6,h:0.42,fontFace:'Aptos',fontSize:15,color:C.muted,margin:0,fit:'shrink'});}
function card(s,x,y,w,h,heading,body,accent=C.blue){s.addShape(pptx.ShapeType.roundRect,{x,y,w,h,rectRadius:0.08,fill:{color:C.panel},line:{color:C.line,width:1}});s.addShape(pptx.ShapeType.rect,{x:x+0.02,y:y+0.02,w:0.06,h:h-0.04,fill:{color:accent},line:{color:accent}});s.addText(heading,{x:x+0.22,y:y+0.18,w:w-0.42,h:0.35,fontSize:15,bold:true,color:C.text,margin:0,fit:'shrink'});s.addText(body,{x:x+0.22,y:y+0.67,w:w-0.42,h:h-0.85,fontSize:12,color:C.muted,margin:0,valign:'top',fit:'shrink'});}
function pill(s,text,x,y,w,color){s.addShape(pptx.ShapeType.roundRect,{x,y,w,h:0.42,rectRadius:0.08,fill:{color,transparency:84},line:{color,transparency:55,width:1}});s.addText(text,{x:x+0.1,y:y+0.09,w:w-0.2,h:0.2,fontSize:10.5,bold:true,color,align:'center',margin:0,fit:'shrink'});}
// 1
{const s=pptx.addSlide('MASTER');s.addText('Resume AI coding work\nonly from verified reality.',{x:0.75,y:1.25,w:9.2,h:1.85,fontFace:'Aptos Display',fontSize:45,bold:true,color:C.text,margin:0,fit:'shrink'});s.addText('A checkpoint can preserve accepted decisions while repository facts become stale. HandoffGuard keeps the first and re-verifies the second.',{x:0.78,y:3.45,w:8.25,h:1.0,fontSize:19,color:C.muted,margin:0,fit:'shrink'});pill(s,'accepted state survives',0.78,5.05,2.6,C.green);pill(s,'material facts re-verify',3.58,5.05,2.9,C.cyan);pill(s,'stale execution blocks',6.68,5.05,2.8,C.amber);s.addShape(pptx.ShapeType.roundRect,{x:9.7,y:1.45,w:2.45,h:4.45,rectRadius:0.08,fill:{color:C.panel},line:{color:C.line}});const rows=[['PASS','initial'],['PASS','unrelated'],['BLOCK','material drift'],['PASS','replan'],['FAIL','test'],['PASS','repair']];let y=1.9;rows.forEach((r,i)=>{const col=r[0]==='PASS'?C.green:r[0]==='BLOCK'?C.amber:C.red;s.addText(r[0],{x:9.98,y,w:0.7,h:0.28,fontSize:10,bold:true,color:col,margin:0});s.addText(r[1],{x:10.7,y,w:1.15,h:0.28,fontSize:10,color:C.muted,margin:0,fit:'shrink'});y+=0.62;});}
//2
{const s=pptx.addSlide('MASTER');title(s,'The handoff problem is two different problems','Continuation state can remain valid while mutable repo facts become stale.');card(s,0.7,2.2,5.7,3.5,'Preserve','Accepted scope\nAccepted decisions\nAuthority boundary\nExact next move\nLineage / transition identity',C.green);card(s,6.8,2.2,5.7,3.5,'Re-verify','Declared material paths + SHA256\nAcceptance command binding\nSource presence\nOptional Git HEAD context\nFinal-current-byte proof',C.cyan);s.addText('Restarting everything loses the left side. Blindly resuming trusts the right side.',{x:1.25,y:6.15,w:10.9,h:0.45,fontSize:17,bold:true,color:C.text,align:'center',margin:0,fit:'shrink'});}
//3
{const s=pptx.addSlide('MASTER');title(s,'Selective continuation','Repo changed ≠ material input changed. HandoffGuard distinguishes them before execution.');const nodes=[['Agent A\nhandoff',C.blue],['Resume\nverify',C.cyan],['Unrelated\nchange',C.green],['Material\ndrift',C.amber],['Fresh-read\n+ re-plan',C.blue],['Execute +\nprove',C.green]];let x=0.55;nodes.forEach((n,i)=>{s.addShape(pptx.ShapeType.roundRect,{x,y:2.7,w:1.72,h:1.25,rectRadius:0.06,fill:{color:C.panel},line:{color:n[1],width:1.3}});s.addText(n[0],{x:x+0.12,y:3.02,w:1.48,h:0.58,fontSize:14,bold:true,color:C.text,align:'center',margin:0,fit:'shrink'});if(i<nodes.length-1)s.addShape(pptx.ShapeType.chevron,{x:x+1.79,y:3.08,w:0.35,h:0.42,fill:{color:C.line},line:{color:C.line}});x+=2.08;});card(s,1.05,4.75,5.2,1.28,'Unrelated repo change','Material hashes still match → PASS_RESUME_BINDING. Do not reopen accepted work.',C.green);card(s,6.65,4.75,5.2,1.28,'Material change','Exact changed path reported → BLOCKED_STALE_HANDOFF before stale execution.',C.amber);}
//4
{const s=pptx.addSlide('MASTER');title(s,'Executable proof sequence','The same acceptance command exposes the regression before the repair and proves the continuation after it.');const rows=[['01','Initial handoff','PASS_RESUME_BINDING',C.green],['02','Unrelated HEAD change','PASS_RESUME_BINDING',C.green],['03','Material source drift','BLOCKED_STALE_HANDOFF',C.amber],['04','Fresh-read + rebind','PASS_RESUME_BINDING',C.green],['05','Unchanged acceptance','FAIL_EXECUTABLE_PROOF',C.red],['06','Repair + rerun','PASS_EXECUTABLE_PROOF',C.green],['07','Final current bytes','PASS_CONTINUATION',C.cyan]];let y=2.05;rows.forEach(r=>{s.addShape(pptx.ShapeType.roundRect,{x:0.75,y,w:11.55,h:0.58,rectRadius:0.04,fill:{color:C.panel},line:{color:C.line}});s.addText(r[0],{x:0.95,y:y+0.14,w:0.35,h:0.22,fontSize:11,bold:true,color:r[3],margin:0});s.addText(r[1],{x:1.45,y:y+0.12,w:3.6,h:0.26,fontSize:12.5,bold:true,color:C.text,margin:0,fit:'shrink'});s.addText(r[2],{x:5.45,y:y+0.12,w:5.95,h:0.26,fontSize:12.2,bold:true,color:r[3],margin:0,fit:'shrink'});y+=0.68;});s.addText('Local full-baseline proof: 14 tests PASS · deterministic sequence match · final adjudication PASS_CONTINUATION',{x:0.95,y:6.75,w:11.0,h:0.3,fontSize:12.2,bold:true,color:C.cyan,align:'center',margin:0,fit:'shrink'});}
//5
{const s=pptx.addSlide('MASTER');title(s,'IBM Bob is in the material path','Bob does repository understanding, stale-state recovery, bounded repair and review.');card(s,0.75,2.15,3.55,3.45,'1  Plan','Read sender handoff + current repo.\nIdentify accepted state vs mutable facts.\nExplain why resume is blocked and which exact path needs fresh-read.',C.blue);card(s,4.55,2.15,3.55,3.45,'2  Agent','Verify stale handoff.\nFresh-read changed path.\nWrite bounded re-plan + successor handoff.\nRun unchanged failing acceptance.\nRepair only the proven defect.\nRerun proof.',C.green);card(s,8.35,2.15,3.55,3.45,'3  Review','Review diff + lineage + receipts.\nCheck no silent scope widening.\nCheck screenshots and public-safe data.\nKeep claims inside executable proof.',C.amber);s.addText('After each task: capture Bob task-session-summary → bob_sessions/',{x:1.55,y:6.15,w:10.1,h:0.38,fontSize:16,bold:true,color:C.text,align:'center',margin:0,fit:'shrink'});}
//6
{const s=pptx.addSlide('MASTER');title(s,'Full baseline first','A reduced variant may replace this only after it proves material net advantage with no material regression.');card(s,0.75,2.05,3.55,3.35,'Full baseline keeps','Accepted-state preservation\nSelective continuation\nStale material-path fail-closed\nFresh-read/re-plan lineage\nExecutable acceptance\nFinal-current-byte adjudication',C.green);card(s,4.55,2.05,3.55,3.35,'Deliberately excluded','Generic orchestration\nCI vendor integrations\nBackend/auth/database\nPrivate data\nAuto-publish\nAuto-submission',C.blue);card(s,8.35,2.05,3.55,3.35,'Claim ceiling','HandoffGuard proves a bounded continuation property.\n\nIt does not claim general correctness, production security, or autonomous authority.',C.amber);s.addText('python demo.py',{x:3.85,y:5.75,w:5.7,h:0.55,fontFace:'Courier New',fontSize:24,bold:true,color:C.cyan,align:'center',margin:0});s.addText('One command reproduces the core story.',{x:4.15,y:6.35,w:5.1,h:0.3,fontSize:14,color:C.muted,align:'center',margin:0});}

pptx.writeFile({fileName:'/mnt/data/handoffguard-full-baseline/presentation/HandoffGuard_IBM_Bob_2_Hackathon.pptx'});
